spring:
  application:
    name: GATWAY-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9196



  gateway:
    mvc:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: order-service
        #                fallbackuri: forword://orderfallback
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: order-service
#                fallbackuri: forword://paymentfallback
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  instance:
#    # Optional, Eureka typically handles this automatically
#    hostname: localhost
server:
  port: 8989